local DB_VERSION = 0.00;

local _, tb = ...;

local MAX_BIT_FLAGS_TUTORIAL = 4294934528;
local cvar_fields = {
	"shipyardMissionTutorialFirst",
	"shipyardMissionTutorialBlockade",
	"shipyardMissionTutorialAreaBuff",
	"lastVoidStorageTutorial",
};
local bit_fields = {
	LE_FRAME_TUTORIAL_9_0_GRRISON_LANDING_PAGE_BUTTON_CALLINGS,
	LE_FRAME_TUTORIAL_9_0_GRRISON_LANDING_PAGE_CALLINGS,
	LE_FRAME_TUTORIAL_9_0_JAILERS_TOWER_BUFFS,
	LE_FRAME_TUTORIAL_ACCCOUNT_CLUB_FINDER_NEW_FEATURE,
	LE_FRAME_TUTORIAL_ANIMA_DIVERSION_ACTIVATE_LOCATION,
	LE_FRAME_TUTORIAL_ANIMA_DIVERSION_REINFORCE_LOCATION,
	LE_FRAME_TUTORIAL_ARTIFACT_APPEARANCE_TAB,
	LE_FRAME_TUTORIAL_ARTIFACT_KNOWLEDGE,
	LE_FRAME_TUTORIAL_ARTIFACT_RELIC_MATCH,
	LE_FRAME_TUTORIAL_AZERITE_FIRST_POWER_LOCKED_IN,
	LE_FRAME_TUTORIAL_AZERITE_ITEM_IN_BAG,
	LE_FRAME_TUTORIAL_AZERITE_ITEM_IN_SLOT,
	LE_FRAME_TUTORIAL_AZERITE_RESPEC,
	LE_FRAME_TUTORIAL_BAG_SETTINGS,
	LE_FRAME_TUTORIAL_BAG_SLOTS_AUTHENTICATOR,
	LE_FRAME_TUTORIAL_BONUS_ROLL_ENCOUNTER_JOURNAL_LINK,
	LE_FRAME_TUTORIAL_BOOSTED_SPELL_BOOK,
	LE_FRAME_TUTORIAL_BOUNTY_FINISHED,
	LE_FRAME_TUTORIAL_BOUNTY_INTRO,
	LE_FRAME_TUTORIAL_BRAWL,
	LE_FRAME_TUTORIAL_CAMPAIGN_LORE_TEXT,
	LE_FRAME_TUTORIAL_CHAT_CHANNELS,
	LE_FRAME_TUTORIAL_CLEAN_UP_BAGS,
	LE_FRAME_TUTORIAL_CLUB_FINDER_LINKING,
	LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_APPLICANTS_GUILD_LEADER,
	LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_COMMUNITY_LEADER,
	LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_LANGUAGE_FILTER,
	LE_FRAME_TUTORIAL_CORRUPTION_CLEANSER,
	LE_FRAME_TUTORIAL_COVENANT_RENOWN_PROGRESS,
	LE_FRAME_TUTORIAL_COVENANT_RENOWN_REWARDS,
	LE_FRAME_TUTORIAL_COVENANT_RESERVOIR_DEPOSIT,
	LE_FRAME_TUTORIAL_COVENANT_RESERVOIR_FEATURES,
	LE_FRAME_TUTORIAL_CROSS_FACTION_COMMUNITY,
	LE_FRAME_TUTORIAL_CROSS_FACTION_GROUP_FINDER,
	LE_FRAME_TUTORIAL_CROSS_FACTION_INVITE,
	LE_FRAME_TUTORIAL_DRACTHYR_EMPOWERED,
	LE_FRAME_TUTORIAL_DRACTHYR_ESSENCE,
	LE_FRAME_TUTORIAL_DRACTHYR_LOW_HEALTH,
	LE_FRAME_TUTORIAL_EDIT_MODE_MANAGER,
	LE_FRAME_TUTORIAL_EMBER_COURT_MAP,
	LE_FRAME_TUTORIAL_EQUIP_REAGENT_BAG,
	LE_FRAME_TUTORIAL_EYE_OF_JAILER,
	LE_FRAME_TUTORIAL_FIRST_RUNEFORGE_LEGENDARY_POWER,
	LE_FRAME_TUTORIAL_FRIENDS_LIST_QUICK_JOIN,
	LE_FRAME_TUTORIAL_GAME_TIME_AUCTION_HOUSE,
	LE_FRAME_TUTORIAL_GARRISON_BUILDING,
	LE_FRAME_TUTORIAL_GARRISON_LANDING,
	LE_FRAME_TUTORIAL_GARRISON_ZONE_ABILITY,
	LE_FRAME_TUTORIAL_GREAT_VAULT_CLASS_SETS,
	LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL,
	LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL_LEVEL,
	LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL_TAB,
	LE_FRAME_TUTORIAL_HONOR_TALENT_FIRST_TALENT,
	LE_FRAME_TUTORIAL_HONOR_TALENT_HONOR_LEVELS,
	LE_FRAME_TUTORIAL_HONOR_TALENT_PRESTIGE,
	LE_FRAME_TUTORIAL_HUD_REVAMP_BAG_CHANGES,
	LE_FRAME_TUTORIAL_HUD_REVAMP_LFG_QUEUE_CHANGES,
	LE_FRAME_TUTORIAL_HUD_REVAMP_TRACKING_CHANGES,
	LE_FRAME_TUTORIAL_HUD_REVAMP_UNIT_FRAME_CHANGES,
	LE_FRAME_TUTORIAL_INVENTORY_FIXUP_CHECK_EXPANSION_LEGION,
	LE_FRAME_TUTORIAL_INVENTORY_FIXUP_EXPANSION_LEGION,
	LE_FRAME_TUTORIAL_ISLANDS_QUEUE_BUTTON,
	LE_FRAME_TUTORIAL_ISLANDS_QUEUE_INFO_FRAME,
	LE_FRAME_TUTORIAL_LFG_LIST,
	LE_FRAME_TUTORIAL_LINK_TRANSMOG_OUTFIT,
	LE_FRAME_TUTORIAL_MAJOR_FACTION_RENOWN_PROGRESS,
	LE_FRAME_TUTORIAL_MOUNT_COLLECTION_DRAGONRIDING,
	LE_FRAME_TUTORIAL_MOUNT_EQUIPMENT_SLOT_FRAME,
	LE_FRAME_TUTORIAL_NEWCOMER_GRADUATION,
	LE_FRAME_TUTORIAL_NEWCOMER_GRADUATION_REMINDER,
	LE_FRAME_TUTORIAL_OPTIONAL_REAGENT_CRAFTING,
	LE_FRAME_TUTORIAL_PET_JOURNAL,
	LE_FRAME_TUTORIAL_PROFESSIONS,
	LE_FRAME_TUTORIAL_PVP_SPECIAL_EVENT,
	LE_FRAME_TUTORIAL_PVP_TALENTS_FIRST_UNLOCK,
	LE_FRAME_TUTORIAL_PVP_WARMODE_UNLOCK,
	LE_FRAME_TUTORIAL_QUEST_SESSION,
	LE_FRAME_TUTORIAL_REAGENT_BANK_UNLOCK,
	LE_FRAME_TUTORIAL_RELIC_FORGE_LEARN_TRAIT,
	LE_FRAME_TUTORIAL_RELIC_FORGE_PREVIEW_RELIC,
	LE_FRAME_TUTORIAL_RELIC_FORGE_SOCKETED_RELIC,
	LE_FRAME_TUTORIAL_REPUTATION_EXALTED_PLUS,
	LE_FRAME_TUTORIAL_RUNECARVER_SCRAPPING,
	LE_FRAME_TUTORIAL_RUNEFORGE_LEGENDARY_CRAFT,
	LE_FRAME_TUTORIAL_SOULBIND_CONDUIT_INSTALL,
	LE_FRAME_TUTORIAL_SOULBIND_CONDUIT_LEARN,
	LE_FRAME_TUTORIAL_SOULBIND_ENHANCED_CONDUIT,
	LE_FRAME_TUTORIAL_SOULBIND_PATH_SELECT,
	LE_FRAME_TUTORIAL_SPEC,
	LE_FRAME_TUTORIAL_SPEC_CHANGES,
	LE_FRAME_TUTORIAL_SPEECH_TO_TEXT,
	LE_FRAME_TUTORIAL_SPELLBOOK,
	LE_FRAME_TUTORIAL_TALENT,
	LE_FRAME_TUTORIAL_TALENT_CHANGES,
	LE_FRAME_TUTORIAL_TALENT_STARTER_HELP,
	LE_FRAME_TUTORIAL_TEXT_TO_SPEECH,
	LE_FRAME_TUTORIAL_TORGHAST_DOMINANCE_BAR,
	LE_FRAME_TUTORIAL_TORGHAST_DOMINANCE_BAR_CUTOFF,
	LE_FRAME_TUTORIAL_TORGHAST_EARN_TOWER_KNOWLEDGE,
	LE_FRAME_TUTORIAL_TORGHAST_REROLL,
	LE_FRAME_TUTORIAL_TORGHAST_SPEND_TOWER_KNOWLEDGE,
	LE_FRAME_TUTORIAL_TOYBOX,
	LE_FRAME_TUTORIAL_TOYBOX_FAVORITE,
	LE_FRAME_TUTORIAL_TOYBOX_MOUSEWHEEL_PAGING,
	LE_FRAME_TUTORIAL_TRADESKILL_RANK_STAR,
	LE_FRAME_TUTORIAL_TRADESKILL_UNLEARNED_TAB,
	LE_FRAME_TUTORIAL_TRANSMOG_JOURNAL_TAB,
	LE_FRAME_TUTORIAL_TRANSMOG_MODEL_CLICK,
	LE_FRAME_TUTORIAL_TRANSMOG_OUTFIT_DROPDOWN,
	LE_FRAME_TUTORIAL_TRANSMOG_SETS_TAB,
	LE_FRAME_TUTORIAL_TRANSMOG_SETS_VENDOR_TAB,
	LE_FRAME_TUTORIAL_TRANSMOG_SPECS_BUTTON,
	LE_FRAME_TUTORIAL_TRIAL_BANKED_XP,
	LE_FRAME_TUTORIAL_UPGRADEABLE_ITEM_IN_SLOT,
	LE_FRAME_TUTORIAL_WARFRONT_CONSTRUCTION,
	LE_FRAME_TUTORIAL_WARFRONT_RESOURCES,
	LE_FRAME_TUTORIAL_WORLD_MAP_FRAME,
	LE_FRAME_TUTORIAL_WORLD_MAP_THREAT_ICON,
	LE_FRAME_TUTORIAL_X,
};

tb.frame = CreateFrame("Frame", "TutorialBusterFrame", UIParent);
tb.frame:RegisterEvent("PLAYER_ENTERING_WORLD");
tb.frame:SetScript("OnEvent", function(self, event, ...)
	return tb[event] and tb[event](tb, ...);
end);

function tb:PLAYER_ENTERING_WORLD(self, ...)
	if (not GetCVar("lastGarrisonMissionTutorial") or tonumber(GetCVar("lastGarrisonMissionTutorial")) < MAX_BIT_FLAGS_TUTORIAL) then
		SetCVar("lastGarrisonMissionTutorial", MAX_BIT_FLAGS_TUTORIAL);
	end
	if (not GetCVar("orderHallMissionTutorial") or tonumber(GetCVar("orderHallMissionTutorial")) < MAX_BIT_FLAGS_TUTORIAL) then
		SetCVar("orderHallMissionTutorial", MAX_BIT_FLAGS_TUTORIAL);
	end

	local _, field;
	for _,field in pairs(cvar_fields) do
		if (tonumber(GetCVar(field)) == 0) then
			SetCVar(field, 1);
		end
	end
	for _,field in pairs(bit_fields) do
		if (not GetCVarBitfield("closedInfoFrames", field)) then
			SetCVarBitfield("closedInfoFrames", field, true);
		end
	end
	
	tb.frame:UnregisterEvent("ADDON_LOADED");
end